substitutions:
  devicename: sp111_07
  upper_devicename: SP111 07
  # Higher value gives lower watt readout
  current_res: "0.00122"
  # Lower value gives lower voltage readout
  voltage_div: "764"

<<: !include sp111_common.yaml
